### ISSUE TITLE
OVE > Sequence map not showing the cut sites

### ISSUE THREAD

**Issue by siobhandavis** [TeselaGen/openVectorEditor#414] opened 2018-11-29 20:02 UTC
_From @XimeMora on October 17, 2018 18:47_

### Describe what's going wrong/what needs to change.
In the Vector Editor the Sequence map is not showing the cut sites the second time that the user selects the option to see them.

_Copied from original issue: TeselaGen/hde#2543_

**Comment by tnrich** [comment] 2019-05-30 20:16
Can you please provide a video reproducing this issue @XimeMora

**Comment by XimeMora** [comment] 2019-05-30 22:10
It seems to be working now. Closing the ticket.

**Closed by XimeMora** 2019-05-30 22:10 UTC
