### ISSUE TITLE
VE not saving Feature Notes in exported Genbank

### ISSUE THREAD

**Issue by jdmccauley** [TeselaGen/openVectorEditor#607] opened 2020-04-09 17:50 UTC
@tnrich
Hi tnrich,

I am a Vector Editor user at JBEI. I found an issue with Vector Editor version 10.1.63 (current version), and in ove-electron. I already reported this issue to ove-electron.

Issue:

I was making edits to a sequence in VE, where I wanted to make a feature and give it a feature note. I was able to do so, and export the sequence as a genbank file.

The exported genbank file did have the new features, but it lacked the feature notes. This was also true if I added a feature note to an existing feature. In all, I noticed that the current version of VE cannot save feature notes when exporting as a genbank file.

If I made edits to the genbank file in a text editor and then imported the edited file into VE, the feature and feature notes were able to be viewed. So VE can view feature notes when importing a genbank file, but it cannot save new feature notes into genbank files.

I hope this issue is helpful, and I can answer any more questions you have about the issue.

Best,
Joshua McCauley

**Comment by tnrich** [comment] 2020-04-09 19:16
Hey @jdmccauley,

So I think the main issue here and why this bug still exists is because genbanks have a bunch of different "note" fields that are a little confusing. Here are some example genbank features with different "notes": 

```
     source          1..947
                     /description="I'm a description"
                     /organism="unspecified"
                     /mol_type="genomic DNA"
                     /note="20bp overlap"
     misc_feature    1..12
                     /note="20bp overlap"
     misc_feature    1..10
                     /note="15bp overlap"
     misc_feature    1..8
                     /note="MCS1"
                     /note="pUC18/19 multiple cloning site"
     source          2903..2915
                     /label=Cloning vector pBBR1MCS-2
                     /organism="Cloning vector pBBR1MCS-2"
                     /lab_host="Bordetella bronchiseptica"
                     /mol_type="genomic DNA"
                     /plasmid="pBBR1MCS-2"
                     /note="modification of cloning vector pBBR1MCS, GenBank
                     Accession Number U02374; gene encoding chloramphenical
                     resistance replaced by gene encoding kanamycin resistance"
                     /vntifkey="98"
                     /db_xref="taxon:39477"
```

Certain of those fields, like label and organism are standardized genbank keys. Certain others like vntifkey might be some user added "note" that we should pass along and allow to be edited. Others, the actual `/note="` are obviously notes, but there can be multiple per annotation. Currently I tried to handle all this complexity by just having a single textAreaField: 
![image](https://user-images.githubusercontent.com/2730609/78931706-30f1ff80-7a5b-11ea-9e01-03565e0c323e.png)
If formatted in that very particular way, the notes field actually does pass along info to the genbank file, its just very non-intuitive to users that they'd need to input their notes like that to get them to save. 

My plan is to update the notes UI to instead look more like this: 
![image](https://user-images.githubusercontent.com/2730609/78932105-cf7e6080-7a5b-11ea-8c93-4ab631b0bef5.png)

Which will make it easier to map to a genbank file.

**Comment by jdmccauley** [comment] 2020-04-09 20:14
Hi @tnrich ,

I see, that's consistent with what I tried. I was editing the genbank with a text editor to add the `/note=""` field to add notes, and I found that the "organism" and other fields were written the same way in the editor. I tried to format notes in Vector Editor like you did, and I wasn't able to get the format correct so they could save (you're right in that it's not intuitive!).

You plan sounds great! Thank you for addressing this. Will the changes be included in ove-electron as well? 

Best,
Josh

**Comment by tnrich** [comment] 2020-04-09 20:20
@jdmccauley yep, the changes will be included in ove-electron. I'll attach links here once everything is released in ove and ove-electron. Here's what the new version is looking like so far: 

![image](https://user-images.githubusercontent.com/2730609/78937175-d6f63780-7a64-11ea-877c-f11167c04a57.png)

**Comment by jdmccauley** [comment] 2020-04-09 20:54
@tnrich 
Awesome, this looks amazing so far! Also, thank you for addressing this so quickly!

**Comment by tnrich** [comment] 2020-04-10 21:08
Hey @jdmccauley I've updated the notes UI and published new version of ove and ove-electron. Let me know if the latest ove-electron release works for you -- https://github.com/tnrich/ove-electron/releases/tag/v0.1.8 

Closing this but please re-open if anything isn't working for you! Thanks again for filing an issue :) I knew this was kind of broken but needed that little push to fix it

**Comment by tnrich** [comment] 2020-04-10 21:09
Here's a screenshot of what that UI should look like: 
![image](https://user-images.githubusercontent.com/2730609/79023331-ec3a9700-7b34-11ea-981a-f89f3e0a3dd0.png)

**Closed by tnrich** 2020-04-10 21:09 UTC

**Comment by jdmccauley** [comment] 2020-04-11 03:08
Hey @tnrich ,

This works great now, thank you! I can save feature notes in both the online instance and in OVE electron.

I want to point out that you cannot save notes (or any other user specified "key") at the same time that you make a new feature. I tried making features, and I noticed that the notes were not saved if I added them in the same pop-up when making the new feature. However, if I made a feature and saved it, I could then make notes that would save if I edited the feature again.

I'm not sure if this worth opening up the issue again, but I wanted to point this out to you at least.

Regardless, the fact that I can save notes (and other attributes) is a life-saver. Thank you for fixing this!

Best,
Josh

**Comment by tnrich** [comment] 2020-04-11 05:36
Haha interesting I think I noticed that but then thought I was maybe seeing things because I didn't know how to reproduce it. I'll write a test for that and fix it and let you know when the new release is out. Good catch!

**Comment by jdmccauley** [comment] 2020-04-11 20:33
I thought the same thing haha, I had to test it a few times to make sure I wasn't seeing things either. Thank you for working on this!

**Comment by tnrich** [comment] 2020-04-13 17:24
@jdmccauley here's the latest: https://github.com/tnrich/ove-electron/releases/tag/v0.1.9

**Comment by jdmccauley** [comment] 2020-04-13 20:31
@tnrich Great, now it saves notes when making new features. Thank you!
