### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by sjpeccoud** [TeselaGen/openVectorEditor#790] opened 2021-11-17 01:34 UTC
I was trying to use the ove react component, so I installed the js package using `yarn add open-vector-editor`. Then I followed the instruction for the code, but every time I start my local server I get the following error. 

```ERROR in ./node_modules/teselagen-react-components/es/style.css (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/postcss-loader/src??ref--5-2!./node_modules/teselagen-react-components/es/style.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Failed to find '~@blueprintjs/core/lib/css/blueprint.css'
in [
.../node_modules/teselagen-react-components/es

.../node_modules/postcss-import/lib/resolve-id.js:35:13

ERROR in ./node_modules/teselagen-react-components/es/DataTable/style.css (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/postcss-loader/src??ref--5-2!./node_modules/teselagen-react-components/es/DataTable/style.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Failed to find '~@teselagen/react-table/react-table.css'
in [
.../node_modules/teselagen-react-components/es/DataTable,
.../node_modules/teselagen-react-components/es
]
at .../node_modules/postcss-import/lib/resolve-id.js:35:13
ℹ ｢wdm｣: Failed to compile.
```

I tried installing the two modules manually but that didn't help at all.
Any suggestions?

@tnrich

**Comment by tnrich** [comment] 2021-11-19 21:38
Hey @sjpeccoud sorry I didn't see your issue sooner!

What kind of machine are you on? Mac/windows/linux? 

Want to set up a time to pair to get it working for you?

-Thoams

**Comment by sjpeccoud** [comment] 2021-11-20 00:22
@tnrich 

No problem! I am on a mac and I am using webpack.
I would love to setup a time to meet. I am available next week Monday from 3-5pm PT, Tuesday anytime, and Wednesday anytime. I am in Pacific Time for what its worth.

Thank you so much,
Samuel

**Comment by tnrich** [comment] 2021-11-20 22:12
Let's do Monday at 3pm PT if that works for you. Also do you have a link to the repo that you're doing this work in? I could try reproducing locally

**Comment by sjpeccoud** [comment] 2021-11-21 18:49
@tnrich Monday at 3 works great. You can send me the invite here: samuel@genofab.com
Unfortunately my repo is private and I am not allowed to share it outside my organization.

**Comment by tnrich** [comment] 2021-11-21 18:54
Sounds good. Sent you an invite. You might want to see if you can replicate
the situation by setting up a share-able example repo. Could be a good
exercise in general and sanity check that things are unfolding as you
think.

**Comment by tnrich** [comment] 2021-11-23 00:26
@sjpeccoud after talking today I think we've determined a few things: 

- The issue is on your side. Running the https://github.com/tnrich/ove-react-demo-repo worked fine for you as did running the ove demo app locally
- It is _probably_ caused by a webpack node-sass/sass/scss loader issue
- just commenting out the lines mentioned above led to another node-sass related issue

My advice would be to 
- first try and see if you can't remove node-sass/sass/scss from your repo entirely and see if that fixes the issue. Do it the quick and dirty way first just nuking any sass related files and then if the approach is successful you'll want to convert them by hand to css. We removed sass and scss from our project and I am very thankful we did because I found it caused near endless configuration issue and made switching to alternate build systems quite the headache. We just tough it out in standard css land.
- If the removing sass/scss approach doesn't work, I'd try setting up an example repo for yourself that mimics your current ruby/webpack set up and play around with loading ove in that more controlled environment.

**Comment by tnrich** [comment] 2021-12-22 03:11
Going to close this for now. Feel free to reopen if you need to or make a new issue!

Good luck!

**Closed by tnrich** 2021-12-22 03:11 UTC
