### ISSUE TITLE
'View Translation' inconsistent behavior

### ISSUE THREAD

**Issue by tiffanydai** [TeselaGen/openVectorEditor#386] opened 2018-10-23 07:58 UTC
feedback from @hplahar: 

![img_2635](https://user-images.githubusercontent.com/35508772/47344837-40f70300-d65e-11e8-8bf4-f2ed1c0f99b6.jpg)
Sometimes no translations show up after clicking 'View Translation', but then when you try to click 'View Translation' again, it tells you that duplicate translations aren't allowed, even though no translations are displayed

@tnrich

**Comment by tnrich** [comment] 2018-10-23 13:18
I cannot reproduce this @tiffanydai @hplahar . Can we check that this is actually an issue on the latest OVE? Making a new translation should now always trigger showing translations.

**Comment by hplahar** [comment] 2018-10-24 17:33
I updated to 5.1.5 on https://j5.jbei.org/VectorEditor/VectorEditor.html and I can still reproduce it

**Comment by tnrich** [comment] 2018-10-24 18:54
@hplahar thanks for the heads up. You are indeed right that there is a logical error in there. Fixing it now. I'll let you know when I've pushed a fix.

**Comment by XimeMora** [comment] 2018-10-25 00:43
This has been fixed!

**Closed** 2019-03-07 23:48 UTC
Labels: Customer: JBEI, Status: 5-Passed QA 1, Type: Fix or Enhance
