### ISSUE TITLE
Resizable Panels

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#159] opened 2017-11-06 16:46 UTC
- [x] Allow the circular view/ row view to be resized by dragging a "splitter" element between them. 
 - [x] Allow the properties view to slide in from the right  as another resizable panel.

**Comment by njhillson** [comment] 2017-11-07 14:50
This is not working for me in ICE - VV. Failing.

**Comment by njhillson** [comment] 2017-11-09 20:27
This is working now. Duplicate of ticket #179.

**Comment by XimeMora** [comment] 2017-11-28 06:40
Looks good!!!

**Closed** 2018-03-12 22:04 UTC
Labels: Priority: 3-Normal, Type: Feature
