### ISSUE TITLE
Unable to remove subviews

### ISSUE THREAD

**Issue by meisenstat** [TeselaGen/openVectorEditor#363] opened 2018-08-10 20:39 UTC
When I open something new inside of OVE, I cannot close it. For example if you make a new alignment, the tab will show up in the right editor. You are able to switch between tabs but you cannot close that tab you just made. My mouse isn't aligning in the screenshot but the 'x' is not working.

![image](https://user-images.githubusercontent.com/13423840/43980344-af9aa758-9ca2-11e8-9ee4-c18d658cd617.png)

**Comment by tnrich** [comment] 2018-08-13 21:12
thanks @meisenstat I'll look into this shortly!

**Comment by tnrich** [comment] 2018-08-14 16:54
also check out licecap https://download.cnet.com/LICEcap/3000-2094_4-75984664.html for creating little gifs of the screen :)

**Comment by tnrich** [comment] 2018-08-14 16:58
Hmm I'm unable to reproduce this @meisenstat , let's pair when you're free ?

**Comment by tnrich** [comment] 2019-03-07 23:55
Closing for now. Let me know if I can help with this @meisenstat

**Closed by tnrich** 2019-03-07 23:55 UTC
Labels: Customer: General, Priority: 3-Normal, Type: Fix or Enhance, languishing
