### ISSUE TITLE
openVE crashing when clicking on "Properties"

### ISSUE THREAD

**Issue by hplahar** [TeselaGen/openVectorEditor#284] opened 2018-03-30 21:42 UTC
This is happening on the latest version on registry-test2. Doesn't happen on older versions I am using in production. When you click on "Properties" when viewing a sequence, it goes blank. There is a stack trace in the console. Copied the first few lines below:

Invariant Violation: Could not find "client" in the context of Mutation. Wrap the root component in an <ApolloProvider>
Stack trace:
invariant@https://unpkg.com/open-vector-editor/umd/open-vector-editor.min.js:22826:15
Mutation/_this.verifyContext@https://unpkg.com/open-vector-editor/umd/open-vector-editor.min.js:50586:17
Mutation@https://unpkg.com/open-vector-editor/umd/open-vector-editor.min.js:50588:13
constructClassInstance@https://unpkg.com/open-vector-editor/umd/open-vector-editor.min.js:105869:81
beginWork@https://unpkg.com/open-vector-editor/umd/open-vector-editor.min.js:105896:154
e@https://unpkg.com/open-vector-editor/umd/open-vector-editor.min.js:105934:105

**Comment by tnrich** [comment] 2018-04-02 16:38
Thanks @hplahar I'll look into this asap

**Comment by tnrich** [comment] 2018-04-02 17:59
This should be fixed now. It was caused by a new warning thrown by one of our dependencies.

**Comment by AdamZMc** [comment] 2018-04-25 18:36
This hasn't been an issue for me. Moving along.

**Comment by XimeMora** [comment] 2018-04-26 04:29
This has been fixed, it's not happening on registry-test2.

**Closed** 2018-08-06 22:55 UTC
Labels: Context: JBEI ICE, Priority: 1-Critical, Status: 6-Passed QA 2, Type: Fix or Enhance
